### ISSUE TITLE
Only lookups the modules just under the specified directory

### ISSUE THREAD

**Issue by pythonissam** [karun012/doctest-discover#13]
```haskell
getAbsDirectoryContents :: FilePath -> IO [FilePath]
getAbsDirectoryContents dir = getDirectoryContents dir >>= mapM (canonicalizePath . (dir </>))
```

With this definition, `doctest-discover` only lookups the modules just under the specified directory and doctests in nested modules are ignored. I think it would be nice if we can run doctests in all modules under the directory recursively. Do you have a plan to change the definition to do this? Thank you.

**Comment by sgraf812** [comment]
This should probably just use the [`Glob`](https://hackage.haskell.org/package/Glob) library, like the [`haskeleton`](https://github.com/tfausak/haskeleton/blob/c0e2b61f99d2ba81ec2055b5f20cc609e487fb76/package-name/test-suite/DocTest.hs) example does. It's so even easy to use that I don't think I need to use this library any longer.

**Comment by karun012** [comment]
Sorry. I've not had any time to look into this. Will put a note in the repo
that it's not being maintained anymore.

**Comment by sgraf812** [comment]
No hard feelings, `Glob` works like a charm.

**Comment by karun012** [comment]
Good to know. Thanks.
