### ISSUE TITLE
Can I pass options to doctest?

### ISSUE THREAD

**Issue by kindaro** [karun012/doctest-discover#20]
Sometimes you actually want to do that. Currently, `doctest` has as many as three command line options. Besides, it has the ability to deliver command line flags to the `ghci` process that it uses to execute tests. So, it would be useful to be able to configure `doctest-discover` to pass options to `doctest`.

**Comment by karun012** [comment]
doctest-discover supports a config file. I can look into adding flags to it so that all the config is in one place.

**Comment by kindaro** [comment]
Since the relevant pull request is merged, I assume this can be closed.
