### ISSUE TITLE
doctest-discover does not work with any of the recent Stack lts build plans

### ISSUE THREAD

**Issue by rcook** [karun012/doctest-discover#4]
I tried building `doctest-discover` using lts-3.16, lts-3.20 and lts-4.0 or nightly:

    $ cd doctest-discover/
    $ stack init
    Writing default config file to: /data/home/rcook/src/doctest-discover/stack.yaml
    Basing on cabal files:
    - /data/home/rcook/src/doctest-discover/doctest-discover.cabal

    Checking against build plan lts-3.20

    * Build plan did not match your requirements:
        base version 4.8.1.0 found
        - doctest-discover requires >=4.6 && <4.8

    Checking against build plan lts-3.16

    * Build plan did not match your requirements:
        base version 4.8.1.0 found
        - doctest-discover requires >=4.6 && <4.8

    Downloaded lts-4.0 build plan.
    Caching build plan
    Fetched package index.
    Populated index cache.
    Checking against build plan lts-4.0

    * Build plan did not match your requirements:
        base version 4.8.2.0 found
        - doctest-discover requires >=4.6 && <4.8

    Downloaded nightly-2016-01-06 build plan.
    Caching build plan
    Checking against build plan nightly-2016-01-06

    * Build plan did not match your requirements:
        base version 4.8.2.0 found
        - doctest-discover requires >=4.6 && <4.8

    There was no snapshot found that matched the package bounds in your .cabal files.
    Please choose one of the following commands to get started.

        stack init --resolver lts-3.20
        stack init --resolver lts-3.16
        stack init --resolver lts-4.0
        stack init --resolver nightly-2016-01-06

This make using `doctest-discover` with Stack-based builds tricky.

**Comment by karun012** [comment]
Thank you for the fix. Merging your PR assuming it works for you locally. Please let me know if you find any other issues. I can't test it on my machine for a few weeks.

**Comment by karun012** [comment]
@rcook I see you did not bump the version. I can bump it and release if you want a new version

**Comment by rcook** [comment]
Yes please. I did not know what your policy on that was, so I thought it best to leave it up to you.

Have you thought about adding this package to Stackage/Stable Hackage (https://github.com/fpco/stackage)?

**Comment by karun012** [comment]
I haven't really used stack in a while. We can add it.

**Comment by karun012** [comment]
@rcook Sorry I haven't had the time to do this. Let me know if it is urgent.

**Comment by rcook** [comment]
@karun012 : No hurry! Thanks.

**Comment by rcook** [comment]
@karun012: Have you thought any more about putting this package in Stackage?

**Comment by karun012** [comment]
Sorry I have been really busy. We can put it up on stackage. Would you be
able to help me out with it?

**Comment by rcook** [comment]
Yes, I'd love to help. I've never added anything to Stackage before, but I've read some of the documentation and it doesn't seem like it should be too difficult. Since it's possible to add packages on behalf of the package author, let me see if I can take care of it for you. I'll let you know if I run into any problems!

**Comment by karun012** [comment]
Thank you. We'll try to setup an automatic deploy to stackage and hackage.
I have auto deploy for hackage from travis on another project. It's fairly
simple.

**Comment by rcook** [comment]
I need to update the Stackage contributors list (https://github.com/fpco/stackage/blob/master/build-constraints.yaml) and need your full name and preferred e-mail. Please let me know what to use for these.

**Comment by karun012** [comment]
You have the right information. Thank you for doing this. Let me know once you're done and I'll make sure I add you to the contributors list.

**Comment by karun012** [comment]
https://github.com/karun012/doctest-discover/commit/27eff688c3f457a5f798b5adc06e4cd45078acf1
