### ISSUE TITLE
Need to push version v0.1.0.7 of package with new base version constraints

### ISSUE THREAD

**Issue by rcook** [karun012/doctest-discover#6]
Commit 1765720c already bumped the version constraints on `base` in order satisfy Stackage LTS constraints. In order to incorporate this package into Stackage, we'll need to bump the version and push a new version to Hackage. I can make the version change, but @karun012 will need to push the new package to Hackage.

See the following build failure for more information: https://travis-ci.org/fpco/stackage/builds/108900011

**Comment by karun012** [comment]
Built and uploaded to Hackage.

**Comment by karun012** [comment]
https://hackage.haskell.org/package/doctest-discover-0.1.0.7
