### ISSUE TITLE
Add doctest-discover to stackage

### ISSUE THREAD

**Issue by angerman** [karun012/doctest-discover#8]
Today I found out that doctest-dicover was not part of stackage; how about adding it?

**Comment by karun012** [comment]
@angerman, @rcook added it a few weeks ago - https://github.com/karun012/doctest-discover/issues/6

**Comment by angerman** [comment]
I see. Completely missed that. So we'll just have to wait until it trickles down into LTS.

**Comment by karun012** [comment]
Not sure if there is a way to get it to LTS faster :)

**Comment by angerman** [comment]
I don't know if there is. Let's see. The next LTS should be available in a couple of days.

**Comment by rcook** [comment]
It's been in the nightlies for a while (e.g. https://www.stackage.org/nightly-2016-03-30/package/doctest-discover-0.1.0.7). I thought it would make its way into LTS automatically. It's also been a couple of months since I added it. I've just sent mail to one of the Stack folks to find out when we can expect to see it in LTS, or if there's something amiss.

**Comment by karun012** [comment]
Thank you for following up, @rcook.

**Comment by rcook** [comment]
I just got clarification from Michael Snoyman (Stack guru):

> New Nightly packages are not automatically added to LTS until the next major version. For more information, see:
>
> https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package-to-an-lts-snapshot"

Here is the summary from `MAINTAINERS.md`:

> The steps above affect the Stackage Nightly builds, but do not directly affect LTS Haskell builds. When we build a new LTS Haskell major version (anything ending in .0), the package set is taken from Stackage Nightly. Therefore, by following the above steps, you can get your package into the next major LTS Haskell release.

Therefore, we'll need to wait until the `lts-6.0` release unless or take a few extra steps to get it into an earlier LTS.

I'll see if I can find some time to get it into the next `lts-5.x` release, but I make no guarantees!

Thanks, Richard

**Comment by karun012** [comment]
Thank you, @rcook. I am busy with a few other things at the moment. So I won't be able to do that either. If you guys make any pull requests I'll be sure to check them out and merge them.
